@baseUrl = http://localhost:5000

POST {{baseUrl}}/level/add
Content-Type: application/json

{
  "name": "Intermediate"
}


###
POST {{baseUrl}}/task/add
Content-Type: application/json

{
  "description": "Function to compute the sum of two numbers",
  "snippet":"function add(a, b) { return a + b; }",
  "level":"645e4d72000bd905103a3bd8"
}

###

POST {{baseUrl}}/user/add
Content-Type: application/json

{
  "uid":"3",
  "roles": ["user"]
}